[project]
name = "variant-effect-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Christian Ramirez", email = "christian.ramirez1@umassmed.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "cherimoya",
    "alphagenome-pytorch>=0.3.1",
    "borzoi-pytorch>=0.5.1",
    "bpnet-lite>=1.0.0",
    "enformer-pytorch>=0.8.11",
    "loguru>=0.7.3",
    "numpy>=2.4.6",
    "polars[all]>=1.41.0",
    "pysam>=0.24.0",
    "rich>=14.3.4",
    "scipy>=1.17.1",
    "submitit>=1.5.4",
    "tangermeme>=1.0.4",
]

[build-system]
requires = ["uv_build>=0.11.16,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "altair>=6.1.0",
    "marimo>=0.23.8",
    "matplotlib>=3.10",
    "pytest>=9.0.3",
    "quak>=0.3.5",
]

[tool.uv]
override-dependencies = ["nvidia-cudnn-cu13==9.21.1.3"]

[tool.uv.sources]
cherimoya = { git = "https://github.com/jmschrei/cherimoya.git" }
